// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$$$$0 from "./sections/About.tsx";
import * as $$$$$$1 from "./sections/ChatApp.tsx";
import * as $$$$$$2 from "./sections/MessageBox.tsx";
import * as $$$$$$3 from "./sections/Peer.tsx";
import * as $$$$$$6 from "./sections/starstuff/StarBG.tsx";
import * as $$$$$$4 from "./sections/Theme/Theme.tsx";
import * as $$$$$$5 from "./sections/Waves.tsx";

const manifest = {
  "sections": {
    "site/sections/About.tsx": $$$$$$0,
    "site/sections/ChatApp.tsx": $$$$$$1,
    "site/sections/MessageBox.tsx": $$$$$$2,
    "site/sections/Peer.tsx": $$$$$$3,
    "site/sections/starstuff/StarBG.tsx": $$$$$$6,
    "site/sections/Theme/Theme.tsx": $$$$$$4,
    "site/sections/Waves.tsx": $$$$$$5,
  },
  "apps": {
    "site/apps/deco/htmx.ts": $$$$$$$$$$$0,
    "site/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
